name: localstoragev2
description: Simple json file-based storage fo flutter. Alternative to react-native AsyncStorage
version: 4.1.0+1
author: Danaila Iulian <lula_canci@yahoo.com>
homepage: https://github.com/lulacanci/flutter_localstorage

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
